import { IUserRating } from 'types/interfaces/rating';

export const list: IUserRating[] = [
  {
    id: 523626,
    username: 'test_mail',
    name: 'Roman2',
    avatar: {
      id: 96,
      image: 'https://magiclime.academy/api/media/Step1_66wFIUR.png',
    },
    league: 3,
    experience: 595,
    rank: 1,
    rank_change: 0,
    about: 'Комплексное зондирование волнового фронта',
  },
  {
    id: 523624,
    username: 'rokbas',
    name: 'Anton',
    avatar: null,
    league: 1,
    experience: 40,
    rank: 1,
    rank_change: 0,
    about: 'Комплексное зондирование волнового фронта',
  },
  {
    id: 654091,
    username: 'maximus',
    name: 'maximus@btclime.business',
    avatar: null,
    league: 1,
    experience: 12,
    rank: 49,
    rank_change: 0,
    about: null,
  },
  {
    id: 523632,
    username: 'Кирилл Левчук',
    name: 'Кирилл',
    avatar: {
      id: 104,
      image: 'https://magiclime.academy/api/media/-CI25iQAtok.jpg',
    },
    league: 1,
    experience: 30,
    rank: 2,
    rank_change: 0,
    about: null,
  },
  {
    id: 741642,
    username: 'test_mail1@mail.ru',
    name: 'Ростислав',
    avatar: {
      id: 101,
      image: 'https://magiclime.academy/api/media/_normal.jpeg',
    },
    league: 1,
    experience: 30,
    rank: 3,
    rank_change: 0,
    about: '',
  },
  {
    id: 523638,
    username: 'Okey4',
    name: 'merlanjan2013@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 45,
    rank_change: 0,
    about: null,
  },
  {
    id: 523640,
    username: 'SabyrMLM',
    name: 'mr.usluga2016@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 47,
    rank_change: 0,
    about: null,
  },
  {
    id: 523636,
    username: 'verbena111',
    name: 'deks555@yandex.ru',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 43,
    rank_change: 0,
    about: null,
  },
  {
    id: 523665,
    username: 'svetlana2208',
    name: 'svetl-os@yandex.ru',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 44,
    rank_change: 0,
    about: null,
  },
  {
    id: 523639,
    username: 'LediSV',
    name: 's.svetlana190276@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 46,
    rank_change: 0,
    about: null,
  },
  {
    id: 523644,
    username: 'captain2',
    name: 'captain2',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 7,
    rank_change: 0,
    about: null,
  },
  {
    id: 523650,
    username: 'madina6670',
    name: 'zamdatali@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 13,
    rank_change: 0,
    about: null,
  },
  {
    id: 523651,
    username: 'Saule',
    name: 'akmama3400@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 14,
    rank_change: 0,
    about: null,
  },
  {
    id: 523652,
    username: 'tamura',
    name: 'madinatle.66@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 15,
    rank_change: 0,
    about: null,
  },
  {
    id: 523661,
    username: 'Larisa76',
    name: '1976la22@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 24,
    rank_change: 0,
    about: null,
  },
  {
    id: 523641,
    username: 'captain',
    name: 'Ivan Ivanov',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 12,
    rank_change: 0,
    about: null,
  },
  {
    id: 523643,
    username: 'captain1',
    name: 'captain1',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 6,
    rank_change: 0,
    about: null,
  },
  {
    id: 523648,
    username: 'Alenka',
    name: 'alenatatarova76@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 11,
    rank_change: 0,
    about: null,
  },
  {
    id: 523658,
    username: 'Zheka0108',
    name: 'evgeniahambazarova33367@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 21,
    rank_change: 0,
    about: null,
  },
  {
    id: 523657,
    username: 'SUPER7',
    name: 'zhannaash9313@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 20,
    rank_change: 0,
    about: null,
  },
  {
    id: 523659,
    username: 'Leila',
    name: 'lekaadam1991@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 22,
    rank_change: 0,
    about: null,
  },
  {
    id: 523660,
    username: 'Uspeh',
    name: 'Alenatatarova76+1@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 23,
    rank_change: 0,
    about: null,
  },
  {
    id: 523647,
    username: 'Liza1981',
    name: 'liza199er@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 10,
    rank_change: 0,
    about: null,
  },
  {
    id: 523671,
    username: 'Pugovka',
    name: 'pugovka7777777@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 25,
    rank_change: 0,
    about: null,
  },
  {
    id: 523656,
    username: 'ELENA',
    name: 'ee0269929@gmail.com',
    avatar: null,
    league: 1,
    experience: 20,
    rank: 19,
    rank_change: 0,
    about: null,
  },
];
